language: node_js

before_install:
  - wget http://www.tortall.net/projects/yasm/releases/yasm-1.3.0.tar.gz
  - tar xvzf yasm-1.3.0.tar.gz && cd yasm*
  - ./configure
  - make
  - sudo make install && cd ..

before_script:
  - "echo 1 | ./chinachu installer"

notifications:
  email: false
